### ISSUE TITLE
Publish Use of Admin Panel with Apache2 as ReverseProxy server

### ISSUE THREAD

**Issue by axiades** [setsal/Laravel-openvpn-admin#5]
Hello,

i want to use your Panel with Apache2 as Webserver configured as ReverseProxy.

How can i start the artisan webserver Permanently?

**Comment by setsal** [comment]
Hi, 

It is not wise to use the builtin webserver in production mode, the `artisan serve` command is just for development.

You can just point the apache web dir in project `public` folder, and the laravel will serve as normally.

More please refer to the official laravel document ( https://laravel.com/docs/7.x/deployment )

Thanks,
setsal

**Comment by axiades** [comment]
what are the default login Credentials for the Panel?

**Comment by setsal** [comment]
Hi,

For security concern, there is not any default login credential and the registration page is closed.

If you want to register a new admin user ( or first time )

Please change the `routes/web.php` line 18 to  `Auth::routes();`

then you will see the register button in the home page

Thanks,
setsal

**Comment by axiades** [comment]
Nice One.

And how can i now Create OpenVPN Users?

**Comment by setsal** [comment]
You need to host your openvpn server with radius plugin by yourself. 

This project is just an admin panel.

After your vpn server and radius server is done, you have to let the radius mysql database connect with the project. You can see more information in `config/database.php`.  (radius_mysql)

Radius sql user default user and password is the same to laravel.

So the easiest way is to give your laravel sql user privilege to access the radius sql.

When all done, once you create radius user in admin panel, then it will create openvpn user.
